= A few tips on modelling things in Scala

Mateusz Kubuszok

== About me

[%step]
* breaking things in Scala for 5+ years
* breaking things for money for 8 years
* breaking things for fun for 16(?) years
* blog at https://kubuszok.com[Kubuszok.com]
* niche https://leanpub.com/jvm-scala-book[Things you need to know about JVM (that matter in Scala)] ebook


== The plan

[%step]
* `case class` es - when, when not
* flat is (often) bad
* `sealed trait` s - not only enums
* one size suits all - doesn't work
* integrations


== `case class` es

=== Warm up

What we get when we do?

[source, scala]
--
case class Value(a: Int, b: String)
--

=== !

[source, scala]
--
class Value(a: Int, b: String)
    extends Product with Serializable {
  def copy(a: Int = a, b: String = b): Value = ...
  override def equals(obj: AnyRef): Boolean = ...
  override def hashCode(): Int = ...
  override def toString(): String = s"Value($a, $b)"
  // ... a lot of methods from Product
}
object Value extends ((Int, String) => Value) {
  def apply(a: Int, b: String): Value = new Value(a, b)
  def unapply(value: Value): Option[(Int, String)] = ...
}
--

[NOTE.speaker]
--
`extends Function` is generated only if we don't create a companion object ourselves. Which explains why sometimes we can use `.tupled` on companion, and why sometimes we have to use eta expanion.
--

=== !

[source, scala]
--
Value(1, "1") == new Value(1, "1") // true
Value(1, "1") == Value(2, "2") // false
Value(1, "1") == Value(1, "2").copy(b = "1") // true

Value(1, "1") match {
  case Value(a, b) => println(s"a: $a, b: $b")
}
--

=== When

[%step]
* we want to represent a value/record
* **all** properties are value types

=== When not

=== !

When there is state

[.fragment]
[source, scala]
--
case class NamedCounter(name: String,
                        var counter: Int = 0) {
  def action(): Unit = counter += 1
}
--

[.fragment]
[source, scala]
--
val counter  = NamedCounter("test")
val counters = scala.collection.immutable.HashSet(counter)
counters(counter) // true
counter.action()
counters(counter) // false
--

[.fragment]
[source, scala]
--
class NamedCounter(val name: String) {
  var counter: Int = 0
  def action(): Unit = counter += 1
}
--

[NOTE.speaker]
--
Value types shouldn't be stateful.
--

=== !

When class describes behavior - especially side effects

[.fragment]
[source, scala]
--
case class DbConnection(user: String,
                        pass: String,
                        url:  String) {
  // perhaps initialize connection?
  def runSql(query: String): Int = ...
}
--

[.fragment]
[source, scala]
--
case class DbConfig(user: String,
                    pass: String,
                    url:  String)

class DbConnection(dbCfg: DbConfig) {
  // behavior
}
--

[NOTE.speaker]
--
Value types aren't behavior. Generating apply doesn't justify using `case class`.
--

=== !

When not all properties are values

[.fragment]
[source, scala]
--
case class KeyPair(publicKey: Array[Byte],
                   privateKey: Array[Byte])
--

[.fragment]
[source, scala]
--
case class KeyPair(publicKey: ArraySeq[Byte],
                   privateKey: ArraySeq[Byte])
--

[NOTE.speaker]
--
Don't put into `case class` values which doesn't implement safe `equals` and `hashCode`. If you imagine nested `case class` es as a tree, all leafs have to have sane implementations.
--

=== Cats Typeclasses

[%step]
* *default* `Eq` should match `.equals`
* do not use `Show` for any business logic, only debugging (same for `.toString`)

[NOTE.speaker]
--
These are my own recommendations.
--


== Flat is (often) bad

=== Flat entity

[source, scala]
--
case class UserAddress(
  id:           UUID,
  userID:       UUID,
  addressLine1: String,
  addressLine2: Option[String],
  city:         String,
  zipCode:      String
)
--

=== Comparison

[source, scala]
--
// check for the same entity and version
address1 == address2

// check for the same entity, maybe different version
address1.id == address2.id

// check for the same address value, maybe different entity
(address1.addressLine1 == address2.addressLine1) &&
  (address1.addressLine2 == address2.addressLine2) &&
  (address1.city == address2.city) &&
  (address1.zipCode == address2.zipCode)
--

[NOTE.speaker]
--
What if you add a new field? Do we remember to update all places? Does the code tells us what we do business-wise?
--

=== Just data things

[source, scala]
--
case class DataRecord(
  name1: String,
  name2: String,
  yetAnotherName: String,
  // ... 20-30 fields more
  metricX: Int,
  metricY: Int
)
--

[NOTE.speaker]
--
Grouping these values into smaller values would help structural sharing on update, passing on only the part that is needed but more importantly
--

=== Nested entity

[source, scala]
--
final case class UserAddress(
  id:   UserAddress.ID,
  data: UserAddress.Data)
object UserAddress {
  type ID = UUID // or AnyVal or tagged or @newtype
  final case class Data(
    userID:  User.ID,
    address: Address)
}
final case class Address(
  addressLine1: String, // other candidates for:
  addressLine2: Option[String], // * type aliases
  city:         String,         // * AnyVals or
  zipCode:      String)         // * @newtypes
--

=== Comparison again

[source, scala]
--
userAddress1 == userAddress2

userAddress1.id == userAddress2.id

userAddress1.data.userID == userAddress2.data.userID

userAddress1.data.address == userAddress2.data.address
--

[NOTE.speaker]
--
Intent is self-evident. `===` and `Eq` can work even better.
--

=== Why people avoid nesting

[.fragment]
Because `.copy`

[.fragment]
[source, scala]
--
userAddress.copy(
  data = userAddress.data.copy(
    address = userAddress.data.address.copy(city = "Yolo")
  )
)
--

[.fragment]
Unnecessarily

[.fragment]
[source, scala]
--
import com.softwaremill.quicklens._ // \o/ \o/ \o/

userAddress.modify(_.data.address).setTo("Yolo")
userAddress.modify(_.data.address).using(_.toUppercase)
--

[NOTE.speaker]
--
...in the domian. On the edge, where they represent DTO or API it might make sense. Lenses are not scary.
--


== `sealed trait` s

=== Enums

[source, scala]
--
sealed trait Color
object Color {
  case object Red extends Color
  case object Blue extends Color
  case object Green extends Color
}
--

[source, scala]
--
(color: Color) match {
  case Color.Red   =>
  case Color.Blue  =>
  case Color.Green =>
}
--

[NOTE.speaker]
--
Exhaustivity check. Enums like that can be improved with Enumeratum. Avoid Enumerations!
--

=== Enumerating valid combinations

[.fragment]
[source, scala]
--
case class UserEmail(currentEmail: String,
                     newEmail:     Option[String] = None,
                     confirmed:    Boolean        = false)
--

[.fragment]
[source, scala]
--
sealed trait UserEmail
object UserEmail {
  case class New(email: String) extends UserEmail
  case class Confirmed(email: String) extends UserEmail
  case class Changing(currentEmail: String,
                      newEmail: String) extends UserEmail
}
--

[NOTE.speaker]
--
Eliminate options and explosion of combinations.
--

=== !

[source, scala]
--
enum UserEmail {
  case New(email: String) extends UserEmail
  case Confirmed(email: String) extends UserEmail
  case Changing(currentEmail: String,
                newEmail: String) extends UserEmail
}
--

[NOTE.speaker]
--
In Dotty.
--

=== !

If `sealed trait` doesn't work for some reason

[source, scala]
--
sealed abstract case class UserEmail private (
  currentEmail: String,
  newEmail:     Option[String],
  confirmed:    Boolean
)
object UserEmail {
  def parse(
    currentEmail: String,
    newEmail:     Option[String] = None,
    confirmed:    Boolean        = false
  ): Either[String, UserEmail] =
    if (/* validation */) Right(new UserEmail(...) {})
    else Left("Illegal combination of parameters")
}
--

[NOTE.speaker]
--
Smart constructor.
`abstract` prevents `.copy` and `.apply`.
`private` prevent `new` outside of this object.
`sealed` prevents `extends`.
`.equals`, `.hashCode`, `.toString` and `unapply` still works.
A lot of cases that used to be handled by smart constructor are handled by Refined Types. In Dotty using opaque types.
--


== A case against uniform modelling

=== !

[.fragment]
Uniform modelling:

[%step]
* design a model
* use if for business logic
* and persistence
* and API

[NOTE.speaker]
--
Typical for Rapid Applications Development. Horror for maintenance.
--

=== !

[.fragment]
Uniform modelling in practice:

[%step]
* design database tables and some objects mapping to them directly
* bend over backwards to manually write JSON codecs for these objects
* define domain in terms of table rows
* alternatively, start with API
* try to shove it to database and back

[NOTE.speaker]
--
Taking a moment to design a model that is simple to understand and hard to use wrong.
--

=== Database Driven Design

[source]
--
users:
+---------+------+-------+-----------+-----------------+
| user_id | name | email | email_new | email_confirmed |
+---------+------+-------+-----------+-----------------+
| uuid    | text | text  | text      | boolean         |
+---------+------+-------+-----------+-----------------+

addresses:
+------------+---------+--------+--------+------+------+
| address_id | user_id | line_1 | line_2 | city | zip  |
+------------+---------+--------+--------+------+------+
| uuid       | uuid    | text   | test   | text | text |
+------------+---------+--------+--------+------+------+
--

=== !

[source, scala]
--
case class User(id:             UUID,
                name:           String,
                email:          String,
                newEmail:       Option[String],
                emailConfirmed: Boolean)

case class Address(id:       UUID,
                   userID:   UUID,
                   position: Int,
                   line1:    String,
                   line2:    Option[String],
                   city:     String,
                   zip:      String)
--

=== !

[source, scala]
--
// Doobie

sql"""INSERT INTO users (
     |  id, name, email, email_new, email_confirmed
     |)
     |VALUE (
     |  ${user.id}, ${user.name}, ${user.email},
     |  ${user.newEmail}, ${user.emailConfirmed}
     |)""".stripMargin.update

sql"""SELECT id, name, email, email_new, email_confirmed
     |FROM users
     |WHERE id = $userID""".stripMargin.query[User]
--

[source, scala]
--
// Slick

class Users(tag: Tag) extends TableQuery[User] {
  // id, name, email, newEmail, emailConfirmed columns
  def * = (id, name, email, newEmail, emailConfirmed) <> (
    User.tupled, User.unapply
  )
}
--

=== !

[source, json]
--
{
  "user": {
    "id": "...",
    "name": "...",
    "addresses": [ { "address_id": "...", ... } ]
  }
}
--

[source, scala]
--
implicit val encoder: Encoder[(User, List[Address])] =
  // manual mapping of models to JSON AST
implicit val decoder: Decoder[(User, List[Address])] =
  // manual mapping of JSON cursor to models
--

=== !

[source, scala]
--
def setPrimaryAddress(user: User, address: Address) =
  for {
    _ <- addressBelongToUser(address, user.id)
    addresses <- getAddressesByUser(user.id)
    newAddresses = addresses
      .filterNot(_.id == address.id)
      .prepend(address)
      .zipWithIndex
      .map { case (a, i) => a.copy(position = i) }
    _ <- newAddresses.traverse(persistAddress)
  } yield newAddresses.head
--

=== Separate models

=== !

[source, scala]
--
case class User(id:   User.ID,
                data: User.Data)
object User {
  case class Data(name:      User.Name,
                  email:     User.Email,
                  addresses: List[Address])
  // also ID, Name, Email and whetever we need
}

case class Address(line1: Address.Line1,
                   line2: Option[Address.Line2],
                   city:  Address.City,
                   zip:   Address.Zip)
object Address { // Line1, Line2, City, Zip }
--

=== !

[source, scala]
--
case class AddressDTO(userID: UUID,
                      index:  Int,
                      line1:  String,
                      line2:  Option[String],
                      city:   String,
                      zip:    String) {
  def toDomain: Address = // might be Either if we validate
    ...
}
object AddressDTO {
  def fromDomain(addrs: List[Address]): List[AddressDTO] =
    ...
}
--

=== !

[source, scala]
--
case class UserDTO(id:             UUID,
                   name:           String,
                   email:          String,
                   newEmail:       Option[String],
                   emailConfirmed: Boolean) {
  def toDomain(addressDtos: List[AddressDTO]): User = ...
}
object UserDTO {
  def fromDomain(user: User): (UserDTO, List[AddressDTO]) =
    ...
}
--

=== !

[source, scala]
--
val (userDTO, addressDTOs) = UserDTO.fromDomain(user)
for {
  _ <- sql"""INSERT INTO users ( ... )
            |VALUE ( ${userDTO.id}, ... )
            |ON CONFLICT (id) UPDATE ..."""
         .stripMargin.update.run
  addrInDB <- ... // fetch
  (toUpsert, toDelete) = compare(addressDTOs, addrInDB)
  _ <- sql"""INSERT INTO address ...
            |ON CONFLICT (user_id, position) UPDATE ..."""
         .stripMargin.update.run // using toUpsert
  _ <- sql"""DELETE FROM addresses WHERE ..."""
         .update.run // using toDelete
} yield ()
--

=== !

[source, scala]
--
for {
  userDTO <-
    sql"""SELECT id, name, email, email_new, email_confirmed
         |FROM users
         |WHERE id = $userID"""
      .stripMargin.query[UserDTO].unique
  addressDTOs <-
    sql"""SELECT ... FROM addresses
         |WHERE user_id = $userID"""
      .stripMargin.query[AddressDTO].as[List]
} yield userDTO.toDomain(addressDTOs)
--

=== !

[source, scala]
--
def setPrimaryAddress(user: User, primary: Address) = {
  val updated = user.modify(_.data.addresses).using {
    addresses =>
      primary :: addresses.filterNot(_ == primary)
  }
  for {
    _ <- persistUser(updated)
  } yield updated
}
--

[source, scala]
--
def setAddressEndpoint(userID:     User.ID,
                       addressAPI: AddressAPI) = for {
  user <- getUser(userID)
  address = addressAPI.toDomain
  updated <- setPrimaryAddress(user, address)
} yield UserAPI.fromDomain(updated)
--


== Integrations

=== Repetitive imports

[source, scala]
--
import doobie._
import doobie.implicits._
import doobie.implicits.javatime._
import doobie.postgres._
import doobie.postgres.implicits._
import doobie.refined.implicits._
import CustomDoobieMeta._
--

=== !

[source, scala]
--
object DoobieSupport
    extends doobie.Aliases // basic functionalities
    with doobie.hi.Modules
    with doobie.syntax.AllSyntax
    with ...
    with doobie.postgres.Instances // Postgres extensions
    with ...
    with doobie.refined.Instances // refined types
    with doobie.util.meta.MetaConstructors // Java Time
    with doobie.util.meta.TimeMetaInstances {
  // custom extensions and Meta instances
}
--

[source, scala]
--
import DoobieSupport._
--

=== !

[source, scala]
--
object TapirSupport
    extends sttp.tapir.Tapir
    with sttp.tapir.TapirAliases
    with sttp.tapir.codec.refined.TapirCodecRefined
    with sttp.tapir.json.jsoniter.TapirJsonJsoniter  {
  // custom Tapir extensions and instances
}
--

[source, scala]
--
import TapirSupport._
--

=== Import by default

[source, scala]
--
// default: import java.lang._, scala._, scala.Predef._

// since 2.13
scalacOptions +=
  "-Yimports:java.lang,scala,scala.Predef,cats.syntax.all"
--

== Questons?


== Thank you!
